---
- name: "Include tasks for {{ ansible_os_family }}"
  include_tasks: "{{ ansible_os_family }}/main.yml"

- name: "Set environment variables"
  set_fact:
    borgbackup_envars_export: "export {{ item.key }}=\"{{ item.value }}\"; {{ borgbackup_envars_export|default('') }}"
  with_dict: "{{ borgbackup_envars }}"
  when: borgbackup_envars is defined and borgbackup_envars

- name: "Create backup repository"
  shell: "{{ borgbackup_envars_export }} borg init --encryption {{ borgbackup_encryption }} {{ borgbackup_reposoitory }}"
  warn: no
  ignore_errors: yes

- name: "Create cron job"
  cron:
    user: root
    weekday: "{{ borgbackup_cron['weekday'] }}"
    hour: "{{ borgbackup_cron['hour'] }}"
    name: "Borg Backup"
    job: "/etc/cron.d/backup"
    state: present
    day: "{{ borgbackup_cron['day'] }}"
    minute: "{{ borgbackup_cron['minute'] }}"
    month: "{{ borgbackup_cron['month'] }}"
  when: borgbackup_cron

- name: "Add environmental variables"
  cron:
    user: root
    env: yes
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ borgbackup_envars }}"
  when: borgbackup_cron is defined and borgbackup_cron

- name: "Create cron job file"
  template:
    dest: "/etc/cron.d/backup"
    src: "backup.j2"
    group: "root"
    mode: "0711"
    owner: "root"
  when: borgbackup_cron
